[build]
  # 静的サイトなのでビルドコマンドは不要
  # command = ""
  
  # 公開ディレクトリ
  publish = "."

[build.environment]
  # Node.jsのバージョンを指定（必要に応じて）
  NODE_VERSION = "18"

# 環境変数の設定例（実際の値はNetlify管理画面で設定）
# [context.production.environment]
#   VITE_GEMINI_API_KEY = "your-actual-api-key-here"

# リダイレクト設定（SPAの場合）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ヘッダー設定（セキュリティ強化）
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://generativelanguage.googleapis.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: https: blob: https://via.placeholder.com; connect-src 'self' https://generativelanguage.googleapis.com https://via.placeholder.com https://cdn.jsdelivr.net; font-src 'self' https://cdn.jsdelivr.net;"

# キャッシュ設定
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
